### ISSUE TITLE
Module errors? Conflicts with urllib3?

### ISSUE THREAD

**Issue by fuuddanni** [joda32/CertCrunchy#1]
Hello, the python script breaks with following output: 
`E:\Github\CertCrunchy>e:\Python34\python3.exe certcrunchy.py --domain google.com

 _____           _   _____                       _
/  __ \         | | /  __ \                     | |
| /  \/ ___ _ __| |_| /  \/_ __ _   _ _ __   ___| |__  _   _
| |    / _ \ '__| __| |   | '__| | | | '_ \ / __| '_ \| | | |
| \__/\  __/ |  | |_| \__/\ |  | |_| | | | | (__| | | | |_| |
 \____/\___|_|   \__|\____/_|   \__,_|_| |_|\___|_| |_|\__, |
                                                        __/ |
                                                       |___/
    Just a silly recon tool...
    @_w_m__

[crt.sh] Checking [google.com]
Traceback (most recent call last):
  File "e:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "e:\Python34\lib\http\client.py", line 1227, in getresponse
    response.begin()
  File "e:\Python34\lib\http\client.py", line 386, in begin
    version, status, reason = self._read_status()
  File "e:\Python34\lib\http\client.py", line 348, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "e:\Python34\lib\socket.py", line 378, in readinto
    return self._sock.recv_into(b)
  File "e:\Python34\lib\ssl.py", line 748, in recv_into
    return self.read(nbytes, buffer)
  File "e:\Python34\lib\ssl.py", line 620, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Python34\lib\site-packages\requests\adapters.py", line 376, in send
    timeout=timeout
  File "e:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "e:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "e:\Python34\lib\site-packages\requests\packages\urllib3\packages\six.py", line 310, in reraise
    raise value
  File "e:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "e:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "e:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='crt.sh', port=443): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "certcrunchy.py", line 420, in <module>
    _potential_hosts = _potential_hosts + getTransparencyNames(domain)
  File "certcrunchy.py", line 234, in getTransparencyNames
    r = requests.get(_transparency_endpoint.format(query=domain), timeout=_timeout)
  File "e:\Python34\lib\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "e:\Python34\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "e:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "e:\Python34\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "e:\Python34\lib\site-packages\requests\adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='crt.sh', port=443): Read timed out. (read timeout=3)`

Lib-Packages are satisfied:
E:\Python34>python3.exe -m pip list
Package     Version
----------- ---------
bits-parser 1.0.0
certifi     2018.4.16
chardet     3.0.4
construct   2.8.12
dnspython   1.15.0
docopt      0.6.2
idna        2.7
pip         18.0
requests    2.9.1
setuptools  18.2
urllib3     1.23

I have change my Censys.io API Key. Other Keys are left to default. 
Seems there is a conflict with urllib3. Do you know how to fix my Issue? 

Thankx

**Comment by joda32** [comment]
Hi,
Thanks for using this script. I've just checked and by default against google.com i get the same timeout error but i get no error for a domain like example.com. The reason for that is because the google.com domain has so many results that the request to crt.sh times out. I've added the -O flag where you can set a http request timeout. For domains such as google you might have to set it quite long, but first test using a domain with fewer results. 

Also, I've added some better exception handling so please update and let me know. Oh, and if you have any suggestions or features you want please let me know.

**Comment by fuuddanni** [comment]
Thanks for your answer, you are right. The Script is working like a Charm, if you Flag Timeout -O etc. 100 against the API.  

Thank you for your attention, i will close this Issue as solved. 

[Resolving] gplm-prod-app.corp.google.com => [64.233.166.129]
[Resolving] agile-stg-app.corp.google.com => [64.233.166.129]
[Resolving] howtogetmo.co.uk => [172.217.20.142]

E:\Github\CertCrunchy>e:\Python34\python3.exe certcrunchy.py -O 100 -d google.com
